<?php
require_once( get_stylesheet_directory() . '/wordpress/initial_data.php' );
// Load scripts
function load_vue_scripts() {
    if (IS_PRODUCTION) {
        wp_register_script( // the app build script generated by Webpack.
			'vendors',
			get_template_directory_uri() . '/dist/js/chunk-vendors.js',
			array(),
			false,
			true
		);

        wp_register_script( // the app build script generated by Webpack.
			'themint/app.js',
			get_template_directory_uri() . '/dist/js/app.js',
			array('vendors'),
			false,
			true
		);		
    } else {
        wp_register_script( // the app build script generated by Webpack.
			'themint/app.js',
			'http://localhost:'. VUE_PORT .'/app.js',
			array(),
			false,
			true
		);

		
	}
	register_endpoints();
	register_initial_data();

	wp_enqueue_script('vendors');
	wp_enqueue_script('themint/app.js');
}
add_action('wp_enqueue_scripts', 'load_vue_scripts', 100);