<?php
require_once( get_stylesheet_directory() . '/wordpress/initial_data.php' );
require_once( get_stylesheet_directory(). '/assets_helper.php');

// Load scripts


function load_vue_scripts() {
    if (IS_PRODUCTION) {
        // wp_register_script( // the app build script generated by Webpack.
		// 	'vendors',
		// 	get_template_directory_uri() . '/dist/js/chunk-vendors.js',
		// 	array(),
		// 	false,
		// 	true
		// );

        // wp_register_script( // the app build script generated by Webpack.
		// 	'app',
		// 	get_template_directory_uri() . '/dist/js/app.js',
		// 	array('vendors'),
		// 	false,
		// 	true
		// );		
    } else {
        // wp_register_script( // the app build script generated by Webpack.
		// 	'app',
		// 	'http://localhost:'. VUE_PORT .'/app.js',
		// 	array(),
		// 	false,
		// 	true
		// );

		
	}
	wp_register_script( 'vendors-js', vuewp_mix('chunk-vendors.js'), array(), '1.0.0', true );
	wp_register_script( 'app-js', vuewp_mix('app.js'), array('vendors-js'), '1.0.0', true );


	register_endpoints();
	register_initial_data();
	
	wp_enqueue_style( 'app-styles', vuewp_mix('app.css'));
	wp_enqueue_script('vendors-js');
	wp_enqueue_script('app-js');
}
add_action('wp_enqueue_scripts', 'load_vue_scripts');